Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Joelcio Facanha Moreira
// Data atual  : 22/02/2019
Var
// Seção de Declarações das variáveis 
area, raio: real;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Entre com o raio: ")
Leia(raio)

area := (3.14159 * (raio * raio))

Escreva("Area igual a: ", area:4:3)

Fimalgoritmo