Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Joélcio Façanha Moreira
// Data atual  : 22/02/2019
Var
// Seção de Declarações das variáveis 
C, F: real;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Entre com a temperatura em graus Cº: ")
Leia(C)

F := ((9 * C + 160)/5)

Escreva("Temperatura em Fahrenheit: ", F:5:3)

Fimalgoritmo