Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Joelcio Façanha Moreira
// Data atual  : 22/02/2019
Var
// Seção de Declarações das variáveis 
C, F: real;

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva("Entre com a temperatura em graus Fº")
 Leia(F)
 
 C := ((F-32)*(5/9))
 
 Escreva("A temperatura em graus Cº:", C:5:2)

Fimalgoritmo