Algoritmo "Escrever_Numeros_1_A_10"
// Disciplina  : Algoritmo
// Professor   : Marcos Fortes
// Descrição   : Sistema para escrever numeros de 1 ate 10
// Autor(a)    : Joelcio Façanha Moreira
// Data atual  : 26/04/2019
Var

  i:inteiro
  
Inicio

  i:= 1
  
  Repita
    Escreva(i:3)
    i:= i + 1
  Ate i > 10
  
  Escreval("")
  
  i:= 1
  
  Enquanto i <= 10 faca
     Escreva(i:3)
     i:= i + 1
  FimEnquanto

Fimalgoritmo