Algoritmo "CondicionalSimples"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/02/2019
Var
// Seção de Declarações das variáveis 
a: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
Escreva("Valor de a: ")
Leia(a)

se (a > 10) entao
   Escreva("A maior que 10: ", a)
senao
   Escreva("A menor que 10: ", a)
fimse

Fimalgoritmo