Algoritmo "EXERCICIO_08"
// Disciplina  : Algoritmos
// Professor   : Marcos Forte
// Descrição   : Apresentar todos os valores numéricos inteiros e ímpares entre 100 e 200.
// Autor(a)    : Joelcio Façanha Moreira
// Data atual  : 07/06/2019
Var
// Seção de Declarações das variáveis 
  i: inteiro

Inicio

  Para i:= 100 Ate 200 Faca
  
    Se ((i mod 2) <> 0)Entao
      Escreva(i)
    FimSe
    
  FimPara

Fimalgoritmo