Algoritmo "EXERCICIO_01"
// Disciplina  : Algoritmos
// Professor   : Marcos Forte
// Descrição   : Apresente todos os números de 0 ao número recebido
//               pelo teclado.
// Autor(a)    : Joelcio Façanha Moreira
// Data atual  : 27/05/2019
Var

  i, numero:inteiro

Inicio

  Escreva("Informe um numero: ")
  Leia(numero)

  Para i:= 0 Ate numero Faca
    Escreva(" ", i)
  FimPara

Fimalgoritmo