Algoritmo "EXERCICIO_03"
// Disciplina  : [Algoritmos]
// Professor   : Marcos Forte
// Descrição   : Ler um número e mostrar o seu antecessor e posterior.
// Autor(a)    : Joélcio Façanha Moreira
// Data atual  : 24/02/2019
Var

  numero:real

Inicio

  Escreva("Digite um número qualquer: ")
  Leia(numero)
  
  Escreval("Antecessor: ", (numero - 1))
  Escreval("Sucessor: ", (numero + 1))

Fimalgoritmo