Algoritmo "EXERCICIO_05"
// Disciplina  : [Algoritmos]
// Professor   : Marcos Forte
// Descrição   : Ler dois números e mostrar a soma dos números.
// Autor(a)    : Joélcio Façanha Moreira
// Data atual  : 24/02/2019
Var

  numero1, numero2, soma:real

Inicio

  Escreva("Digite o primeiro número: ")
  Leia(numero1)
  
  Escreva("Digite o segundo número: ")
  Leia(numero2)
  
  soma := (numero1 + numero2)
  
  Escreva("Soma = ", soma:5:2)

Fimalgoritmo