Algoritmo "EXERCICIO_12"
// Disciplina  : [Algoritmos]
// Professor   : Marcos Forte
// Descrição   : Calcular a área de uma circunferência
// Autor(a)    : Joélcio Façanha Moreira
// Data atual  : 24/02/2019
Var

  area, raio: real

Inicio

  Escreva("Informe o raio da circunferência: ")
  Leia(raio)
  
  area := (3.14159 * (raio * raio))
  
  Escreva("A área da circunferência é : ", area:5:2)

Fimalgoritmo