Algoritmo "EXERCICIO_02"
// Disciplina  : [Algoritmos]
// Professor   : Marcos Forte
// Descrição   : Ler e Mostrar os dois número lidos
// Autor(a)    : Joélcio Façanha Moreira
// Data atual  : 24/02/2019
Var

  numero1, numero2: real

Inicio

  Escreva("Digite o primeiro número: ")
  Leia(numero1)
  
  Escreva("Digite o segundo número: ")
  Leia(numero2)
  
  Escreval("Primeiro número digitado foi: ", numero1)
  Escreval("Segundo número digitado foi: ", numero2)

Fimalgoritmo